# Generated by Django 4.1 on 2023-03-23 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='like',
        ),
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 23, 10, 12, 32, 31254, tzinfo=datetime.timezone.utc)),
        ),
    ]
