# Generated by Django 4.1 on 2023-03-23 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_idea_dislikes_alter_idea_date_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 14, 16, 24, 663323, tzinfo=datetime.timezone.utc)),
        ),
    ]
