# Generated by Django 4.1 on 2023-03-23 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_alter_idea_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 14, 55, 40, 934753, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
