# Generated by Django 4.1 on 2023-03-23 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_alter_idea_date_alter_idea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 15, 9, 30, 395271, tzinfo=datetime.timezone.utc)),
        ),
    ]
