# Generated by Django 4.1 on 2023-03-24 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_alter_idea_date_alter_idea_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 9, 23, 7, 828410, tzinfo=datetime.timezone.utc)),
        ),
    ]
